### PR TITLE
Fix printf warnings

### PR DESCRIPTION
**Pull request by basicmaster**

### CODE REVIEW

**Comment by EionRobb** [comment]
Is `%zu` valid on win32?

**Comment by basicmaster** [comment]
Yes. This conversion specifier is part of the C language itself and therefore platform-independent. See the `z` column/`u` row combination in the big table at https://en.cppreference.com/w/c/io/fprintf referring to `size_t`.

**Comment by EionRobb** [comment]
`skypeweb_contacts.c:619:2: error: unknown conversion type character 'z' in format [-Werror=format]
skypeweb_contacts.c:619:2: error: unknown conversion type character 'z' in format [-Werror=format]`

**Comment by EionRobb** [comment]
Using G_GSIZE_FORMAT instead seems to work better for me on win32, does that work on Linux?

**Comment by basicmaster** [comment]
Hmm...what compiler (version) do you use? According to the docs, `z` requires at least C99. Maybe it has to be enabled explicitely.

I haven't tried `G_GSIZE_FORMAT`, but also if it worked, it may be by chance only - in contrast to the platform-agnostic `z`.

**Comment by EionRobb** [comment]
Ah, mingw32 is only c89

**Comment by basicmaster** [comment]
Have you considered [moving to MinGW64](https://en.wikipedia.org/wiki/MinGW#Programming_language_support) (in contrast to its name, it is available for 32 and 64 bit)?? I guess this won't be the last time that issues occur due to only C89 support ;-)

**Comment by EionRobb** [comment]
Pidgin 2.x is still built with minw32 so for now we'll stick with it :)

**Comment by basicmaster** [comment]
OK, I see :-)

So [a workaround](https://stackoverflow.com/questions/44382862/how-to-printf-a-size-t-without-warning-in-mingw-w64-gcc-7-1/44383330#44383330) is required to address this limitation. I just added it the code. On Linux, it works as expected, without warnings.

**Comment by basicmaster** [comment]
@EionRobb Is there any update here in the meantime?

**Comment by EionRobb** [comment]
Sorry for the delay merging this :(

Thanks for the contribution!

**Pull request merged**
