### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by priscila225**
Minor: Missing get in apt command @ README description

### CODE REVIEW

**Comment by EionRobb** [comment]
Is the `apt` command not working for you?

**Comment by dietmarw** [comment]
Some older debian machines don't have `apt` available. So basically anything that does not include the new [apt 1.0 package](https://mvogt.wordpress.com/2014/04/04/apt-1-0/). In contrast `apt-get` would work on all machines, new and older.

**Comment by priscila225** [comment]
Ok, it's work now. Thanks for the explain that. :+1:

**Comment by dietmarw** [comment]
Actually my point was that it makes sense to have the README using `apt-get` just like your PR suggests. So I'd reopen it and ask @EionRobb to accept it to make the instructions working on all kind of debian flavours (including old ones).

**Comment by EionRobb** [comment]
Thanks all.   `apt` is way more handy than `apt-get` but if it's not new enough to be everywhere then it's probably safer to not require it just now :)

**Pull request merged**
