### PR TITLE
Give a detailed login failure message

### PR DESCRIPTION
**Pull request by timgws**
This small change will give you a message and error code back from Skype when the login fails. For example, it will tell you that your account is blocked, or that you are required to enter a 2FA value.

### CODE REVIEW

**Comment by EionRobb** [comment]
Oh nice, that's handy.  Would this just be for the non-alternate login?

**Comment by timgws** [comment]
@EionRobb I believe so.

**Comment by timgws** [comment]
Here are a list of messages that I have seen:

```
   * 80041012: Your account or password is incorrect.
   * Login error: Authentication failed. Bad username or password. (code 40120)
   * Login error: Bad username or password (Authentication Failure)
````

**Comment by xss** [comment]
Hello Tim. Thank you, yes, that sounds very handy. However, there is a typo `error_test` vs `error_text` in `skypeweb_login.c` that causes the `make` to fail until corrected. Just as a side note. :)

**Comment by timgws** [comment]
Ah, sorry about that. I accidentally pushed the unamended commit yesterday.

**Pull request merged**
