### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by intika**
Fix this :
Fatal error when loading a chat
g_log: skypeweb_set_mood_message: assertion `mood' failed

### CODE REVIEW

**Comment by dequis** [comment]
You can just update a PR by pushing more commits without closing it and opening a new one

**Comment by intika** [comment]
thanks for the info ;)

**Comment by EionRobb** [comment]
Happy to bring through 	e024b07 but the other commits aren't correct, as a) there's already a `g_return_if_fail()` which checks if the mood text is `NULL`, and b) the correct fix is to unset the mood on the server if the mood text is `NULL`

**Comment by EionRobb** [comment]
Oh, e024b07 was already pulled via https://github.com/EionRobb/skype4pidgin/pull/509

**Pull request closed without merging**
