### PR TITLE
Some cmake improvements for skypeweb

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by EionRobb** [comment]
Does `PKG_CONFIG_EXECUTABLE` need to be set somewhere?

**Comment by hasufell** [comment]
no, it's set by the cmake module FindPkgconfig

**Comment by EionRobb** [comment]
Should FindPkgConfig be added to the cmake then instead of the PkgConfig package?

**Comment by hasufell** [comment]
> Should FindPkgConfig be added to the cmake then instead of the PkgConfig package?

No, the usage as it is right now is correct. [This line](https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/CMakeLists.txt#L15) will set the required variable.

**Comment by EionRobb** [comment]
Great, thanks for explaining that :)

**Pull request merged**
