### PR TITLE
skypeweb: don't set runtime deps manually

### PR DESCRIPTION
**Pull request by monsta**
Having shlibdeps on is enough to generate proper runtime deps from build-deps. And actually, having both shlibdeps and manually set deps leads to duplicates in the resulting package's deps. You can check it, for example, with `aptitude show skypeweb`.

Before:

```
Depends: libc6 (>= 2.14), libglib2.0-0 (>= 2.28.0), libjson-glib-1.0-0 (>= 0.12.0), libpurple0 (>= 2.10.12), libpurple0 (>= 2.10.0), libglib2.0-0 (>= 2.24),
         libjson-glib-1.0-0 (>= 0.8.0)
```

After:

```
Depends: libc6 (>= 2.14), libglib2.0-0 (>= 2.28.0), libjson-glib-1.0-0 (>= 0.12.0), libpurple0 (>= 2.10.12)
```

As you can see, auto-generated runtime deps are just fine.

Tested in LMDE 2 (Linux Mint Debian Edition) which is based on Debian Jessie.

### CODE REVIEW

**Comment by EionRobb** [comment]
Would you instead change the 'after' to use the lower versioned libglib2, json-glib-1 and libpurple0?  Or is that what is intended with the explicitly defined versions in the depends section?

**Comment by monsta** [comment]
That's what is autogenerated in my system. On other Debian/Ubuntu versions it might be slightly different.

**Comment by EionRobb** [comment]
I guess the concern is, if the deb is built on your machine and it specifies those minimum versions, then people on older deb-based systems wouldn't be able to install the package.

Is there a way to combine both this change, as well as specifying a minimum version of a package?

**Comment by monsta** [comment]
> I guess the concern is, if the deb is built on your machine and it specifies those minimum versions, then people on older deb-based systems wouldn't be able to install the package.

Yes, and usually it's so in Debian repos. For example, a lot of packages from current Debian Testing can't be installed in Debian Stable due to this. But some of them can be rebuilt in Stable so they'd get lower auto-generated runtime deps, and so they could be installed then.

> Is there a way to combine both this change, as well as specifying a minimum version of a package?

Well, when building packages with standard files like ```debian/control```, ```debian/rules``` and so on, usually a special variable ```${shlibs:Depends}``` is specified in runtime deps (in addition to explicit runtime deps, if any). Here it doesn't work if I add it... I get syntax error when running cmake. (Sorry, I'm not really familiar with this build system, I'm more used to autotools. :smile:)

**Comment by EionRobb** [comment]
Does @edhelas have any comments about this? (since he's the one to blame for initially writing it :+1: )

**Comment by dequis** [comment]
Sounds like it would be better to nuke `set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)` instead. I've never been a fan of shlibdeps, seems fragile, but my debian environment is a bit unusual so maybe it's just me.

**Comment by edhelas** [comment]
@EionRobb I'm not sure about the best way to do it but `shlibdeps` seems to be a good solution to automatically detect the dependencies of the packages. We can give it a try :) If the result is ok we can remove the manually set dependencies.

**Comment by monsta** [comment]
The point is that shlibdeps is already on... which, combined with manually set deps, causes the duplicates.

**Comment by monsta** [comment]
I don't use this plugin anymore, so I guess I'll close this.

**Pull request closed without merging**
