### PR TITLE
fix for auto-build packages

### PR DESCRIPTION
**Pull request by BOPOHA**
fixes spec for [work with OBS] (https://build.opensuse.org/package/show/home:BOPOHA/purple-skypeweb) + creating RPMs from main tarball master.tar.gz .
It's needed for creating [ready to use] (https://software.opensuse.org/download.html?project=home%3ABOPOHA&package=purple-skypeweb) package repositories.

### CODE REVIEW

**Comment by EionRobb** [comment]
Does this handle skypeweb being in a subfolder of the master.tar.gz?

**Comment by BOPOHA** [comment]
directory structure of tarball must be contain that dir : "skype4pidgin-*/skypeweb/".
for example:
skype4pidgin-master/skypeweb/
skype4pidgin-0.1/skypeweb/
skype4pidgin-0.1+git.1438548319.fbf1776/skypeweb/

**Comment by EionRobb** [comment]
Thanks :)

**Comment by BOPOHA** [comment]
Ok, Let's try to add integration service:
pic-20150803-081203

pic-20150803-081522
string="R8X5NXodOPIkbJV+qPlgXEleDoXXlrOJQx0OLRd1" 
project="home:BOPOHA" 
package="purple-skypeweb"

It'll be send  command "rebuild packages"  on each commit.

**Comment by BOPOHA** [comment]
and, 
if you wish, 
i can fully transfer project purple-skypeweb to your account on https://build.opensuse.org

**Comment by xvitaly** [comment]
You shouldn't use rpmbuild -ba  ~/rpmbuild/SPECS/purple-skypeweb.spec and download all archive with legacy projects.

**Comment by BOPOHA** [comment]
@xvitaly , 
i can't see problem. what is wrong?

now, you can to download full tarball, and build one of legacy (purple-skypeweb) project with spec file.
only three simple step, without git, tar, etc.: fetch tarball, fetch spec, rpmbuild -ba spec.
p.s. i agree, better to use "-bb" instead "-ba".
p.s. p.s. [to better to use](https://software.opensuse.org/download.html?project=home%3ABOPOHA&package=purple-skypeweb)

**Comment by xvitaly** [comment]
```
Resolving Dependencies
--> Running transaction check
---> Package pidgin-skypeweb.x86_64 0:0.1+git.1438634770.1b8a91c-1.2 will be installed
--> Processing Dependency: skype4pidgin for package: pidgin-skypeweb-0.1+git.1438634770.1b8a91c-1.2.x86_64
--> Finished Dependency Resolution
Error: Package: pidgin-skypeweb-0.1+git.1438634770.1b8a91c-1.2.x86_64 (home_BOPOHA)
           Requires: skype4pidgin
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by xvitaly** [comment]
@BOPOHA 
Fixed this. Pull request: https://github.com/EionRobb/skype4pidgin/pull/323

**Comment by BOPOHA** [comment]
@xvitaly , i'm so sorry, but i did not test the package pidgin-skypeweb at all.  only one purple-skypeweb.

@EionRobb , what about  integration service? ;)

**Pull request merged**
